config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  namespace :cv do
    resources :educations
  end

  # Defines the root path route ("/")
  root "cv#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/cv.rb
module CV
  def self.table_name_prefix
    "cv_"
  end
end

app/models/cv/base_info.rb
class CV::BaseInfo < ApplicationRecord
end

app/models/cv/education.rb
class CV::Education < ApplicationRecord
  validates :institution, presence: true
  validates :degree, presence: true
  validates :to_month, inclusion: { in: 1..12 }
end

app/models/cv/work_role.rb
class CV::WorkRole < ApplicationRecord
  belongs_to :work_tenure, class_name: "CV::WorkTenure", foreign_key: "cv_work_tenures_id"

  validates :position, uniqueness: { scope: :cv_work_tenures_id }
end

app/models/cv/work_tenure.rb
class CV::WorkTenure < ApplicationRecord
  validates :from_month, inclusion: { in: 1..12 }
  validates :to_month, inclusion: { in: 1..12, allow_nil: true }

  has_many :roles, class_name: "CV::WorkRole", dependent: :destroy, foreign_key: :cv_work_tenures_id

  def start_date=(date)
    self.from_month = date.month
    self.from_year = date.year
  end

  def end_date=(date)
    self.to_month = date.month
    self.to_year = date.year
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/cv/educations_controller.rb
class CV::EducationsController < ApplicationController
  def show
    render CV::Educations::Show.new(education)
  end

  def edit
    render CV::Educations::Edit.new(education)
  end

  def update
    education.update!(education_params)
    redirect_to root_url
  rescue ActiveRecord::RecordInvalid
    render CV::Educations::Edit.new(education)
  end

  def destroy
    education.destroy!
    redirect_to root_url
  end

  private

  def education
    CV::Education.find(params[:id])
  end

  def education_params
    params.require(:cv_education).permit(:institution, :degree, :to_month, :to_year)
  end
end

app/controllers/cv/work_roles_controller.rb
class CV::WorkRolesController < ApplicationController
  def edit
    @role = CV::WorkRole.find(params[:id])
  end

  def update
    @role = CV::WorkRole.find(params[:id])
    @role.update(role_params)
    render partial: "cv/work_role", locals: { role: @role }
  end

  private

  def role_params
    params.require(:cv_work_role).permit(:title, :summary)
  end
end

app/controllers/cv/work_tenures_controller.rb
class CV::WorkTenuresController < ApplicationController
  def edit
    @tenure = CV::WorkTenure.find(params[:id])
  end

  def update
    @tenure = CV::WorkTenure.find(params[:id])
    @tenure.update(tenure_params)
    render partial: "cv/work_tenure", locals: { tenure: @tenure }
  end

  private

  def tenure_params
    params.require(:cv_work_tenure).permit(:employer, :from_month, :from_year, :to_month, :to_year, :to_present)
  end
end

app/controllers/cv_controller.rb
class CVController < ApplicationController
  def index; end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  def edit
    @education = CV::Education.find(params[:id])
  end

  def update
    @education = CV::Education.find(params[:id])
    @education.update(education_params)
    render partial: "cv/education", locals: { education: @education }
  end

  private

  def education_params
    params.require(:cv_education).permit(:institution, :degree, :to_month, :to_year)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if (user = User.find_by(email_address: params[:email_address]))
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if (user = User.authenticate_by(params.permit(:email_address, :password)))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cv_helper.rb
module CVHelper
end

app/views/cv/_education.html.erb
<%= turbo_frame_tag dom_id(education, :edit) do %>
  <li class="p-2">
    <h3 class="font-bold"><%= education.institution %></h3>
    <h4 class="italic"><%= education.degree %></h4>
    <%= education.to_month %>/<%= education.to_year %>
    <% if authenticated? -%>
      <div class="float-right">
        <%= link_to icon("fa-solid", "pen-to-square"), edit_cv_education_path(education), aria: { label: "Edit Education" } %>
        &nbsp;&nbsp;
        <%= link_to icon("fa-solid", "trash-can"), cv_education_path(education), data: {
                                                                                   turbo_method: :delete,
                                                                                   turbo_confirm: 'Are you sure?'
                                                                                 },
                                                                                 aria: { label: "Delete Education" } %>
      </div>
    <% end -%>
  </li>
<% end %>

app/views/cv/_educations.html.erb
<%= turbo_frame_tag :cv_educations do %>
  <section id="education" class="basis-1/3">
    <h2 class="font-bold text-3xl">Education</h2>
    <ol>
      <% educations.each do |education| -%>
        <%= render partial: "cv/education", locals: { education: education } %>
      <% end -%>
    </ol>
    <% if authenticated? %>
      <%= turbo_frame_tag :cv_education_new do %>
        <%= link_to icon("fa-solid", "square-plus", "Add Education"), new_cv_education_path, class: "float-right", aria: { label: "Add Education" } %>
      <% end %>
    <% end %>
  </section>
<% end %>

app/views/cv/_work_role.html.erb
<%= turbo_frame_tag dom_id(role, :edit) do %>
  <h4 class="italic"><%= role.title %></h4>
  <p class="pl-4 py-2 pr-32 text-sm"><%= role.summary %></p>
  <% if authenticated? -%>
    <div class="float-right">
      <%= link_to "Edit", edit_cv_work_role_path(role), class: "px-4 border-2 rounded-lg" %>
    </div>
  <% end -%>
<% end %>

app/views/cv/_work_tenure.html.erb
<%= turbo_frame_tag dom_id(tenure, :edit) do %>
  <li class="p-2">
    <h3 class="font-bold"><%= tenure.employer %></h3>
    <%= tenure.from_month %>/<%= tenure.from_year %> to
    <%= tenure.to_present? ? 'Present' : "#{tenure.to_month}/#{tenure.to_year}" %>
    <% if authenticated? -%>
      <div class="float-right">
        <%= link_to "Edit", edit_cv_work_tenure_path(tenure), class: "px-4 border-2 rounded-lg" %>
      </div>
    <% end -%>
    <hr />
    <% tenure.roles.each do |role| %>
      <%= render partial: 'cv/work_role', locals: { role: role } %>
    <% end %>
  </li>
<% end %>

app/views/cv/educations/edit.html.erb
<%= turbo_frame_tag dom_id(@education, :edit) do %>
  <%= form_for @education do |f| %>
    <label>Institution: <%= f.text_field :institution, class: "border-2" %></label><br/>
    <label>Degree: <%= f.text_field :degree, class: "border-2" %></label><br/>
    <label>
      Graduated:
      <%= f.select :to_month, (1..12).to_a %>
      <%= f.select :to_year, (2000..(Date.current.year + 5)).to_a %>
    </label><br/>
    <%= f.submit class: "px-4 border-2 rounded-lg" %>
  <% end %>
<% end %>

app/views/cv/educations/new.html.erb
<%= turbo_frame_tag :cv_education_new do %>
  <%= form_for @education do |f| %>
    <label>Institution: <%= f.text_field :institution, class: "border-2" %></label><br/>
    <label>Degree: <%= f.text_field :degree, class: "border-2" %></label><br/>
    <label>
      Graduated:
      <%= f.select :to_month, (1..12).to_a %>
      <%= f.select :to_year, (2000..(Date.current.year + 5)).to_a %>
    </label><br/>
    <%= f.submit class: "px-4 border-2 rounded-lg" %>
  <% end %>
<% end %>

app/views/cv/index.html.erb
<%= render CV::Summary.new %>
<%= render CV::Experience.new %>
<%= render CV::Educations::List.new %>

app/views/cv/work_roles/edit.html.erb
<%= turbo_frame_tag dom_id(@role, :edit) do %>
  <%= form_for @role do |f| %>
    <label>Title: <%= f.text_field :title, class: "border-2" %></label><br/>
    <label>Summary: <%= f.textarea :summary, class: "border-2" %></label><br/>
    <%= f.submit class: "px-4 border-2 rounded-lg" %>
  <% end %>
<% end %>

app/views/cv/work_tenures/edit.html.erb
<%= turbo_frame_tag dom_id(@tenure, :edit) do %>
  <%= form_for @tenure do |f| %>
    <label>Employer: <%= f.text_field :employer, class: "border-2" %></label><br/>
    <label>
      From:
      <%= f.select :from_month, (1..12).to_a %>
      <%= f.select :from_year, (2000..(Date.current.year + 5)).to_a %>
    </label><br/>
    <label>
      To:
      <%= f.select :to_month, (1..12).to_a %>
      <%= f.select :to_year, (2000..(Date.current.year + 5)).to_a %>
    </label><br/>
    <label>Present? <%= f.checkbox :to_present %></label><br/>
    <%= f.submit class: "px-4 border-2 rounded-lg" %>
  <% end %>
<% end %>

app/views/educations/_show.html.erb
<% education ||= @education %>
<%= turbo_frame_tag dom_id(education, :edit) do %>
  <li class="p-2">
    <h3 class="font-bold"><%= education.institution %></h3>
    <h4 class="italic"><%= education.degree %></h4>
    <%= education.to_month %>/<%= education.to_year %>
    <% if authenticated? -%>
      <div class="float-right">
        <%= link_to "Edit", edit_education_path(education), class: "px-4 border-2 rounded-lg" %>
      </div>
    <% end -%>
  </li>
<% end %>

app/views/educations/edit.html.erb
<%= turbo_frame_tag dom_id(@education, :edit) do %>
  <%= form_for @education, url: education_path(@education) do |f| %>
    <label>Institution: <%= f.text_field :institution, class: "border-2" %></label><br/>
    <label>Degree: <%= f.text_field :degree, class: "border-2" %></label><br/>
    <label>
      Graduated:
      <%= f.select :to_month, (1..12).to_a %>
      <%= f.select :to_year, (2000..(Date.current.year + 5)).to_a %>
    </label><br/>
    <%= f.submit class: "px-4 border-2 rounded-lg" %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Personal Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "css-zero/reset", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "css-zero/variables", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "css-zero/utilities", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="header-layout">
    <header id="header">
      <div class="container">
        <h1 class="font-bold text-2xl">Personal Blog</h1>
      </div>
    </header>

    <main id="main">
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>